### PR TITLE
Littlesis docker version 1.0.3

### LINKED ISSUE #26: sassc 2.2.0 is non-portable
`sassc` 2.2.0 has become non-portable, leading to `illegal instruction` errors on some platforms.

See https://github.com/sass/sassc-ruby/issues/146#issuecomment-534197168

This can be solved temporarily on individual installs by simply reinstalling the gem, but it would be better to prebuild a portable gem.

### PR DESCRIPTION
**Pull request by robjlucas**
Resolves #26

### CODE REVIEW

**Comment by robjlucas** [comment]
@aepyornis this depends on a new version of the docker image which I have not yet been able to push to the docker repo due to insufficient permissions.

**Comment by robjlucas** [comment]
Note to self: just requires a `sudo docker push littlesis/littlesis:1.0.3` once permissions have been elevated.

**Comment by aepyornis** [comment]
thanks! there's one more line where the version has to be changed: https://github.com/public-accountability/littlesis-main/blob/master/docker-compose.yml#L5

**Comment by robjlucas** [comment]
> thanks! there's one more line where the version has to be changed: https://github.com/public-accountability/littlesis-main/blob/master/docker-compose.yml#L5

Sorry if I'm missing something here @aepyornis, but aren't you looking at `master`, which would be changed here by the merging of this PR anyway?

**Comment by aepyornis** [comment]
> Sorry if I'm missing something here @aepyornis, but aren't you looking at `master`, which would be changed here by the merging of this PR anyway?

whoops. I meant to send this: https://github.com/public-accountability/littlesis-main/blob/master/Makefile#L1

**Comment by aepyornis** [comment]
I have a [shortcut to build a new docker image](https://github.com/public-accountability/littlesis-main/blob/master/Makefile#L29-L30) in the makefile: `make build-rails-docker`

**Comment by robjlucas** [comment]
> I have a [shortcut to build a new docker image](https://github.com/public-accountability/littlesis-main/blob/master/Makefile#L29-L30) in the makefile: `make build-rails-docker`

👍 thanks!

**Pull request merged**
